name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make scripts executable
        run: |
            chmod +x scripts/*.sh

      - name: Install dependencies
        run: go mod download

      - name: Build the Go application
        run: go build -o main main.go

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PEM_CONTENT }}

      - name: Zip build files
        run: |
          zip my-application.zip main index.html

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to CodeDeploy
        uses: sourcetoad/aws-codedeploy-action@v1.11.0
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          codedeploy_name: ori-goweb
          codedeploy_group: ori-goapplication-DG
          archive: my-application.zip
          s3_bucket: oriserve-assess-1
          
     

     
