name: Deploy to EC2 with Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: go mod download

      - name: Build and deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          INSTANCE_ID: ${{ secrets.INSTANCE_ID }}
          PEM_CONTENT: ${{ secrets.PEM_CONTENT }}
        run: |
          go build -o main main.go
          scp -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -i <(echo "$PEM_CONTENT") main ec2-user@${INSTANCE_ID}:/home/ec2-user/
          ssh -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -i <(echo "$PEM_CONTENT") ec2-user@${INSTANCE_ID} '
            sudo systemctl stop nginx
            sudo mv /home/ec2-user/main /usr/share/nginx/html/
            sudo systemctl start nginx
          '

      - name: Verify deployment
        run: curl http://${INSTANCE_ID}:9090
