name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: go mod download

      - name: Build the Go application
        run: go build -o main main.go

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PEM_CONTENT }}

      - name: Zip build files
        run: |
          zip my-application.zip main index.html

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload to S3
        run: |
          aws s3 cp my-application.zip s3://oriserve-assess-1/my-application.zip

      - name: Create temporary SSH key file
        run: |
          echo "$PEM_CONTENT" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key

      - name: Copy and deploy build app file to EC2
        run: |
          scp -i /tmp/ssh_key -o StrictHostKeyChecking=no main ubuntu@ec2-3-84-54-107.compute-1.amazonaws.com:/home/ubuntu/
          scp -i /tmp/ssh_key -o StrictHostKeyChecking=no index.html ubuntu@ec2-3-84-54-107.compute-1.amazonaws.com:/home/ubuntu/

      - name: Running application to EC2       
        run: |          
          ssh -i /tmp/ssh_key -o StrictHostKeyChecking=no ubuntu@ec2-3-84-54-107.compute-1.amazonaws.com << EOF
          chmod +x main
          screen -d -m ./main       
          EOF

      - name: Verify deployment
        run: curl http://ec2-3-84-54-107.compute-1.amazonaws.com:9090
