name: Deploy to EC2 with Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: go mod download

      - name: Build the Go application
        run: go build -o main main.go

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PEM_CONTENT }}  # Your PEM key stored in GitHub Secrets

      - name: Create temporary SSH key file
        run: |
             echo "$PEM_CONTENT" > /tmp/ssh_key
             chmod 600 /tmp/ssh_key

      - name: Deploy application to EC2       
        run: |          
            ssh -i /tmp/ssh_key ubuntu@ec2-54-237-192-232.compute-1.amazonaws.com -o StrictHostKeyChecking=no << EOF  
            sudo apt update
            sudo snap install go --channel=1.21/stable --classic
            git clone https://github.com/tshivanshu358/oriserve_assignment.git   
            cd oriserve_assignment
            go run main.go        
            EOF

      - name: Verify deployment
        run: curl http://${{ secrets.INSTANCE_ID }}:80


